name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Compile AHK to EXE
      uses: nekocodeX/GitHub-Action-Ahk2Exe@main
      with:
        in: muteApp.ahk
        out: muteApp.exe
    
    - name: Create Release Package
      run: |
        $tag = "${{ github.ref_name }}"
        $releaseName = "MuteApp-$tag"
        New-Item -ItemType Directory -Path "$releaseName/MuteApp" -Force
        Copy-Item "muteApp.exe" -Destination "$releaseName/MuteApp"
        Copy-Item "SoundVolumeView.exe" -Destination "$releaseName/MuteApp"
        Compress-Archive -Path "$releaseName" -DestinationPath "$releaseName.zip"
      shell: pwsh
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: MuteApp-*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
