name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # 需要完整的提交历史来生成更新日志
    
    - name: Generate Changelog
      id: changelog
      uses: heinrichreimer/github-changelog-generator-action@v2.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        output: CHANGELOG.md
        stripGeneratorNotice: true
        unreleased: false
        sinceTag: ${{ github.ref_name }}
        
    - name: Read Changelog
      id: read_changelog
      shell: pwsh
      run: |
        $changelog = Get-Content CHANGELOG.md -Raw
        $changelog = $changelog -replace "`r`n","%0A"
        echo "::set-output name=changelog::$changelog"

    - name: Compile AHK to EXE
      uses: nekocodeX/GitHub-Action-Ahk2Exe@main
      with:
        in: muteApp.ahk
        out: muteApp.exe
    
    - name: Create Release Package
      run: |
        $tag = "${{ github.ref_name }}"
        $releaseName = "MuteApp-$tag"
        New-Item -ItemType Directory -Path "$releaseName/MuteApp" -Force
        Copy-Item "muteApp.exe" -Destination "$releaseName/MuteApp"
        Copy-Item "nircmd.exe" -Destination "$releaseName/MuteApp"
        Copy-Item "nircmdc.exe" -Destination "$releaseName/MuteApp"
        Compress-Archive -Path "$releaseName" -DestinationPath "$releaseName.zip"
      shell: pwsh
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: MuteApp-*.zip
        body: ${{ steps.read_changelog.outputs.changelog }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
